version: 2.1

jobs:
  test:
    docker:
        - image: cimg/ruby:2.5.9
    steps:
      - run: 
          name: execute rake
          command: bundle exec rake

workflows:
  version: 2
  bundle:
    jobs:
      - test
